import type { MvuConfig, MvuVariableDefinition, MvuRewriteOptions } from "../schemas/mvu.js";
import { analyzeMvuPaths } from "./mvu-path-analyzer.js";

export interface MvuVariableSummary { path: string[]; expression: string; kind: MvuVariableDefinition["kind"]; defaultValue?: unknown; min?: number; max?: number; enumValues?: string[]; description?: string; readonly?: boolean; hidden?: boolean; updateRule?: string }
export interface MvuVariableListResult { variables: MvuVariableSummary[]; warnings: string[] }
export interface MvuVariableEditResult { mvu: MvuConfig; variables: MvuVariableSummary[]; warnings: string[]; changed_path?: string[]; created?: boolean; removed?: boolean }
const TEMPLATE_IMPORT = "import { registerMvuSchema } from 'https://testingcf.jsdelivr.net/gh/StageDog/tavern_resource/dist/util/mvu_zod.js';";

export function listMvuVariables(mvu: Pick<MvuConfig, "schemaScript" | "initvar" | "updateRules">): MvuVariableListResult {
  const analysis = analyzeMvuPaths(mvu);
  return { variables: analysis.schema_paths.map((item) => ({ path: item.segments, expression: item.expression, kind: item.kind, defaultValue: item.default_value, enumValues: item.enum_values, readonly: item.readonly, hidden: item.hidden })), warnings: analysis.parse_warnings.map((w) => w.message) };
}
export function upsertMvuVariable(mvu: MvuConfig, variable: MvuVariableDefinition, rewrite: MvuRewriteOptions = defaultRewrite()): MvuVariableEditResult { assertRelativePath(mvu, variable.path); const listed = listMvuVariables(mvu); const key = keyOf(variable.path); const normalized = normalizeVariable(variable); const created = !listed.variables.some((item) => keyOf(item.path) === key); const variables = created ? [...listed.variables, normalized] : listed.variables.map((item) => keyOf(item.path) === key ? normalized : item); const rewritten = rewriteMvuVariables(mvu, variables, rewrite); return { ...rewritten, changed_path: variable.path, created }; }
export function removeMvuVariable(mvu: MvuConfig, path: string[], rewrite: MvuRewriteOptions = defaultRewrite()): MvuVariableEditResult { assertRelativePath(mvu, path); const listed = listMvuVariables(mvu); const key = keyOf(path); const variables = listed.variables.filter((item) => keyOf(item.path) !== key); const rewritten = rewriteMvuVariables(mvu, variables, rewrite); return { ...rewritten, changed_path: path, removed: variables.length !== listed.variables.length }; }
export function rewriteMvuVariables(mvu: MvuConfig, definitions: MvuVariableDefinition[] | MvuVariableSummary[], rewrite: MvuRewriteOptions = defaultRewrite()): MvuVariableEditResult { const variables = mergeVariables(definitions.map((value) => "expression" in value ? value as MvuVariableSummary : normalizeVariable(value as MvuVariableDefinition))); return { mvu: { ...mvu, ...(rewrite.schemaScript ? { schemaScript: buildSchemaScript(variables) } : {}), ...(rewrite.initvar ? { initvar: buildInitvar(variables, mvu.variableListPath ?? "stat_data") } : {}), ...(rewrite.updateRules ? { updateRules: buildUpdateRules(variables, mvu.variableListPath ?? "stat_data") } : {}) }, variables, warnings: [] }; }

function defaultRewrite(): MvuRewriteOptions { return { schemaScript: true, initvar: true, updateRules: true, outputFormat: false }; }
function assertRelativePath(mvu: MvuConfig, path: string[]): void { const root = mvu.variableListPath ?? "stat_data"; if (path[0] === root) throw new Error(`path 应相对于 variableListPath，不要包含 ${root} 前缀`); }
function normalizeVariable(def: MvuVariableDefinition): MvuVariableSummary { const expression = def.schemaExpression ?? buildExpression(def); return { path: def.path, expression, kind: def.kind, defaultValue: def.defaultValue, min: def.min, max: def.max, enumValues: def.enumValues, description: def.description, readonly: def.readonly ?? def.path.at(-1)?.startsWith("_"), hidden: def.hidden ?? def.path.at(-1)?.startsWith("$"), updateRule: def.updateRule }; }
function buildExpression(def: MvuVariableDefinition): string { const desc = def.description ? `.describe(${JSON.stringify(def.description)})` : ""; const prefault = def.defaultValue !== undefined ? `.prefault(${literal(def.defaultValue)})` : ""; switch (def.kind) { case "number": { const min = def.min ?? 0, max = def.max ?? 100, d = def.defaultValue ?? min; return `z.coerce.number()${desc}.transform(v => _.clamp(v, ${min}, ${max})).prefault(${literal(d)})`; } case "boolean": return `z.boolean()${desc}.prefault(${literal(def.defaultValue ?? false)})`; case "enum": { const values = def.enumValues ?? (typeof def.defaultValue === "string" ? [def.defaultValue] : []); if (!values.length) throw new Error("enum 变量必须提供 enumValues 或 defaultValue"); return `z.enum(${literal(values)})${desc}.prefault(${literal(def.defaultValue ?? values[0])})`; } case "record": return `z.record(z.string(), z.string())${desc}${def.defaultValue === undefined ? ".prefault({})" : prefault}`; case "object": return `z.object({})${desc}${def.defaultValue === undefined ? ".prefault({})" : prefault}`; case "custom": if (!def.schemaExpression) throw new Error("kind=custom 必须提供 schemaExpression"); return def.schemaExpression; default: return `z.string()${desc}.prefault(${literal(def.defaultValue ?? "")})`; } }
function mergeVariables(vars: MvuVariableSummary[]): MvuVariableSummary[] { const map = new Map<string, MvuVariableSummary>(); for (const variable of vars) map.set(keyOf(variable.path), variable); return [...map.values()].sort((a, b) => keyOf(a.path).localeCompare(keyOf(b.path), "zh-Hans-CN")); }
function buildSchemaScript(vars: MvuVariableSummary[]): string { return `${TEMPLATE_IMPORT}\n\nexport const Schema = z.object({\n${buildObjectFields(vars, 1)}\n});\n\n$(() => {\n  registerMvuSchema(Schema);\n});`; }
function buildObjectFields(vars: MvuVariableSummary[], level: number): string { const grouped = new Map<string, MvuVariableSummary[]>(); const leaves: MvuVariableSummary[] = []; for (const v of vars) { if (v.path.length === level) leaves.push(v); else { const key = v.path[level - 1]; grouped.set(key, [...(grouped.get(key) ?? []), v]); } } const lines: string[] = []; for (const [key, children] of grouped) lines.push(`${indent(level)}${propertyKey(key)}: z.object({\n${buildObjectFields(children, level + 1)}\n${indent(level)}})`); for (const leaf of leaves) lines.push(`${indent(level)}${propertyKey(leaf.path.at(-1) ?? "变量")}: ${leaf.expression}`); return lines.map((line, i) => `${line}${i === lines.length - 1 ? "" : ","}`).join("\n"); }
function buildInitvar(vars: MvuVariableSummary[], rootKey: string): string { const root: Record<string, unknown> = { [rootKey]: {} }; for (const v of vars) setNested(root[rootKey] as Record<string, unknown>, v.path, v.defaultValue ?? defaultForKind(v.kind)); return yamlLines(root).join("\n"); }
function buildUpdateRules(vars: MvuVariableSummary[], rootKey: string): string { const root: Record<string, unknown> = { [rootKey]: {} }; for (const v of vars.filter((item) => !item.readonly)) setNested(root[rootKey] as Record<string, unknown>, v.path, { readonly: Boolean(v.readonly), hidden: Boolean(v.hidden), rule: v.updateRule ?? defaultRule(v) }); return ["变量更新规则:", ...yamlLines(root, 1)].join("\n"); }
function setNested(target: Record<string, unknown>, path: string[], value: unknown): void { let current = target; for (const [i, key] of path.entries()) { if (i === path.length - 1) current[key] = value; else { if (!current[key] || typeof current[key] !== "object" || Array.isArray(current[key])) current[key] = {}; current = current[key] as Record<string, unknown>; } } }
function yamlLines(value: Record<string, unknown>, level = 0): string[] { const lines: string[] = []; for (const [key, child] of Object.entries(value)) { if (child && typeof child === "object" && !Array.isArray(child)) { lines.push(`${"  ".repeat(level)}${key}:`); lines.push(...yamlLines(child as Record<string, unknown>, level + 1)); } else if (Array.isArray(child)) { lines.push(`${"  ".repeat(level)}${key}:`); for (const item of child) lines.push(`${"  ".repeat(level + 1)}- ${String(item)}`); } else lines.push(`${"  ".repeat(level)}${key}: ${String(child ?? "")}`); } return lines; }
function keyOf(path: string[]): string { return path.join("\u0000"); }
function literal(value: unknown): string { return JSON.stringify(value); }
function indent(level: number): string { return "  ".repeat(level); }
function propertyKey(key: string): string { return /^[A-Za-z_$][\w$]*$/.test(key) ? key : JSON.stringify(key); }
function defaultForKind(kind: MvuVariableDefinition["kind"]): unknown { if (kind === "number") return 0; if (kind === "boolean") return false; if (kind === "record" || kind === "object") return {}; return ""; }
function defaultRule(variable: MvuVariableSummary): string { return variable.kind === "number" ? "根据互动自然变化，范围保持克制" : "根据当前场景、对话内容和关系变化更新为简短明确的值"; }
