import type { MvuConfig } from "../schemas/mvu.js";
import { issue, type ValidationIssue } from "./validation-types.js";

export interface MvuVariablePath { path: string; segments: string[]; kind: "string" | "number" | "boolean" | "enum" | "record" | "object" | "custom"; expression: string; has_default: boolean; default_value?: unknown; enum_values?: string[]; readonly: boolean; hidden: boolean }
export interface MvuPathAnalysis { schema_paths: MvuVariablePath[]; initvar_paths: string[]; update_rule_paths: string[]; readonly_paths: string[]; hidden_paths: string[]; parse_warnings: ValidationIssue[] }

export function analyzeMvuPaths(mvu: Pick<MvuConfig, "schemaScript" | "initvar" | "updateRules">): MvuPathAnalysis {
  const parse_warnings: ValidationIssue[] = [];
  const schema_paths = parseSchemaPaths(mvu.schemaScript, parse_warnings);
  const initvar_paths = parseYamlLeafPaths(mvu.initvar, "initvar", parse_warnings);
  const update_rule_paths = parseYamlLeafPaths(mvu.updateRules.replace(/^\s*变量更新规则\s*:\s*$/m, ""), "updateRules", parse_warnings).map((path) => path.replace(/\.(?:type|range|check)$/, ""));
  return { schema_paths, initvar_paths, update_rule_paths: [...new Set(update_rule_paths)], readonly_paths: schema_paths.filter((item) => item.readonly).map((item) => item.path), hidden_paths: schema_paths.filter((item) => item.hidden).map((item) => item.path), parse_warnings };
}
export function toUiPath(path: string): string { return path === "stat_data" || path.startsWith("stat_data.") ? path : `stat_data.${path}`; }
export function fromUiPath(path: string): string { return path.startsWith("stat_data.") ? path.slice("stat_data.".length) : path; }
export function normalizePath(path: string): string { return fromUiPath(path).replace(/^\/+/, "").replace(/^stat_data\//, "").replace(/\//g, ".").replace(/\.+/g, ".").replace(/^\.|\.$/g, ""); }

function parseSchemaPaths(script: string, warnings: ValidationIssue[]): MvuVariablePath[] { const body = extractSchemaObjectBody(script, warnings); return body ? flattenObjectBody(body, [], warnings) : []; }
function extractSchemaObjectBody(script: string, warnings: ValidationIssue[]): string | undefined { const marker = /export\s+const\s+Schema\s*=\s*z\.object\s*\(/g.exec(script); if (!marker) { if (script.trim()) warnings.push(issue({ code: "mvu.schema.missing_schema_object", field: "schemaScript", severity: "warning", message: "未能解析 export const Schema = z.object(...)" })); return undefined; } const start = script.indexOf("{", marker.index + marker[0].length); if (start < 0) return undefined; const end = findMatching(script, start, "{", "}"); if (end < 0) return undefined; return script.slice(start + 1, end); }
function flattenObjectBody(body: string, prefix: string[], warnings: ValidationIssue[]): MvuVariablePath[] { const vars: MvuVariablePath[] = []; for (const entry of splitTopLevel(body, ",")) { const parsed = parseProperty(entry); if (!parsed) { if (entry.trim()) warnings.push(issue({ code: "mvu.schema.unparsed_entry", field: "schemaScript", severity: "warning", message: `跳过无法解析的变量定义：${entry.trim().slice(0, 80)}` })); continue; } const path = [...prefix, parsed.key]; const expression = parsed.value.trim(); const nested = extractDirectObjectExpressionBody(expression); if (nested) vars.push(...flattenObjectBody(nested, path, warnings)); else vars.push({ path: path.join("."), segments: path, kind: inferKind(expression), expression, has_default: /\.(?:prefault|default)\s*\(/.test(expression), default_value: extractDefault(expression), enum_values: extractEnumValues(expression), readonly: path.at(-1)?.startsWith("_") ?? false, hidden: path.at(-1)?.startsWith("$") ?? false }); } return vars; }
function parseYamlLeafPaths(value: string, field: string, warnings: ValidationIssue[]): string[] { if (!value.trim()) return []; const stack: Array<{ indent: number; key: string }> = []; const paths = new Set<string>(); const lines = value.split(/\r?\n/); for (const [lineIndex, raw] of lines.entries()) { const line = raw.replace(/#.*$/, ""); if (!line.trim() || /^\s*-\s/.test(line)) continue; const match = /^(\s*)([^:\n]+):(?:\s*(.*))?$/.exec(line); if (!match) { if (/^\s*[^\s].+/.test(line)) warnings.push(issue({ code: "mvu.yaml.unparsed_line", field, severity: "warning", message: `${field} 第 ${lineIndex + 1} 行无法按 YAML key: value 解析` })); continue; } const indent = match[1].replace(/\t/g, "  ").length; const key = stripYamlKey(match[2].trim()); const rest = match[3] ?? ""; while (stack.length > 0 && stack.at(-1)!.indent >= indent) stack.pop(); const current = [...stack.map((item) => item.key), key]; const next = lines.slice(lineIndex + 1).find((item) => item.trim() && !item.trim().startsWith("#")); const nextIndent = next ? /^\s*/.exec(next)?.[0].replace(/\t/g, "  ").length ?? 0 : 0; if (rest.trim() !== "" || !next || nextIndent <= indent) paths.add(current.join(".")); stack.push({ indent, key }); } return [...paths].filter((p) => p !== "变量更新规则").map(normalizePath); }
function parseProperty(entry: string): { key: string; value: string } | undefined { const trimmed = entry.trim(); if (!trimmed) return undefined; const colon = findTopLevelColon(trimmed); if (colon < 0) return undefined; const key = parseKey(trimmed.slice(0, colon).trim()); const value = trimmed.slice(colon + 1).trim().replace(/,$/, ""); return key && value ? { key, value } : undefined; }
function parseKey(raw: string): string | undefined { if (/^[A-Za-z_$\p{L}][\p{L}\p{N}_$]*$/u.test(raw)) return raw; if ((raw.startsWith("\"") && raw.endsWith("\"")) || (raw.startsWith("'") && raw.endsWith("'"))) return raw.slice(1, -1); if (!/[\s{}()[\],]/.test(raw)) return raw; return undefined; }
function stripYamlKey(key: string): string { return ((key.startsWith("\"") && key.endsWith("\"")) || (key.startsWith("'") && key.endsWith("'"))) ? key.slice(1, -1) : key; }
function extractDirectObjectExpressionBody(expression: string): string | undefined { const trimmed = expression.trim(); const match = /^z\.object\s*\(/.exec(trimmed); if (!match) return undefined; const start = trimmed.indexOf("{", match.index + match[0].length); if (start < 0) return undefined; const end = findMatching(trimmed, start, "{", "}"); if (end < 0) return undefined; return /^\)\s*$/.test(trimmed.slice(end + 1).trim()) ? trimmed.slice(start + 1, end) : undefined; }
function splitTopLevel(value: string, sep: string): string[] { const out: string[] = []; let start = 0, quote: string | undefined, escaped = false; const stack: string[] = []; for (let i = 0; i < value.length; i++) { const c = value[i]; if (quote) { if (escaped) escaped = false; else if (c === "\\") escaped = true; else if (c === quote) quote = undefined; continue; } if (c === "\"" || c === "'" || c === "`") quote = c; else if ("({[".includes(c)) stack.push(c); else if (")}]".includes(c)) stack.pop(); else if (c === sep && stack.length === 0) { out.push(value.slice(start, i)); start = i + 1; } } out.push(value.slice(start)); return out; }
function findTopLevelColon(value: string): number { let quote: string | undefined, escaped = false; const stack: string[] = []; for (let i = 0; i < value.length; i++) { const c = value[i]; if (quote) { if (escaped) escaped = false; else if (c === "\\") escaped = true; else if (c === quote) quote = undefined; continue; } if (c === "\"" || c === "'" || c === "`") quote = c; else if ("({[".includes(c)) stack.push(c); else if (")}]".includes(c)) stack.pop(); else if (c === ":" && stack.length === 0) return i; } return -1; }
function findMatching(value: string, start: number, open: string, close: string): number { let depth = 0, quote: string | undefined, escaped = false; for (let i = start; i < value.length; i++) { const c = value[i]; if (quote) { if (escaped) escaped = false; else if (c === "\\") escaped = true; else if (c === quote) quote = undefined; continue; } if (c === "\"" || c === "'" || c === "`") quote = c; else if (c === open) depth++; else if (c === close && --depth === 0) return i; } return -1; }
function inferKind(expression: string): MvuVariablePath["kind"] { if (/z\.coerce\.number|z\.number/.test(expression)) return "number"; if (/z\.boolean/.test(expression)) return "boolean"; if (/z\.enum/.test(expression)) return "enum"; if (/z\.(?:record|partialRecord)/.test(expression)) return "record"; if (/z\.object/.test(expression)) return "object"; return /z\./.test(expression) ? "string" : "custom"; }
function extractDefault(expression: string): unknown { const match = expression.match(/\.(?:prefault|default)\s*\(([^)]*)\)/); if (!match) return undefined; const t = match[1].trim(); try { return JSON.parse(t); } catch { /* noop */ } if (/^-?\d+(?:\.\d+)?$/.test(t)) return Number(t); if (t === "true") return true; if (t === "false") return false; return t.replace(/^[']|[']$/g, "").replace(/^[\"]|[\"]$/g, ""); }
function extractEnumValues(expression: string): string[] | undefined { const match = expression.match(/z\.enum\s*\(\s*(\[[^\]]*\])/); if (!match) return undefined; try { const parsed = JSON.parse(match[1].replace(/'/g, "\"")); return Array.isArray(parsed) ? parsed.map(String) : undefined; } catch { return undefined; } }
