export type ToolUsageGuide = {
  tool: string;
  purpose: string;
  when_to_call: string;
  required_fields: string[];
  example_input: unknown;
  common_mistakes: string[];
  next_tools: string[];
};

const GUIDES: Record<string, ToolUsageGuide> = {
  get_worldbook_workflow: {
    tool: "get_worldbook_workflow",
    purpose: "根据用户任务类型返回推荐 MCP tool 调用流程。",
    when_to_call: "用户刚提出写世界书、角色卡、查询或修改已有世界书需求时。",
    required_fields: ["task_type"],
    example_input: { task_type: "from_text", wants_character_card: true },
    common_mistakes: ["跳过工作流直接生成 JSON", "角色卡需求未设置 wants_character_card=true"],
    next_tools: ["ingest_text_source", "ingest_web_research", "submit_extraction_result"],
  },
  ingest_text_source: {
    tool: "ingest_text_source",
    purpose: "把用户提供的原始文本、设定、小说片段保存到 MCP project。",
    when_to_call: "用户提供了文本材料时。",
    required_fields: ["title", "content"],
    example_input: { title: "角色设定", content: "...", source_type: "notes", tags: ["角色"] },
    common_mistakes: ["把提取后的结构化事实传到这里", "content 为空"],
    next_tools: ["create_extraction_outline"],
  },
  ingest_web_research: {
    tool: "ingest_web_research",
    purpose: "保存主 AI 搜索网页后整理出的摘要和 facts。MCP 本身不联网搜索。",
    when_to_call: "主 AI 已完成网页搜索并整理摘要后。",
    required_fields: ["topic", "items"],
    example_input: { topic: "作品名", items: [{ title: "页面", url: "https://example.com", summary: "摘要", facts: ["事实"], reliability: "wiki" }] },
    common_mistakes: ["传入未经整理的大段网页 HTML", "省略事实来源 URL"],
    next_tools: ["create_extraction_outline"],
  },
  create_extraction_outline: {
    tool: "create_extraction_outline",
    purpose: "返回主 AI 应提取的角色、世界观、物品、事件字段模板。",
    when_to_call: "原始文本或网页摘要已存入 project 后。",
    required_fields: [],
    example_input: { project_id: "project_xxx", focus: ["characters", "world", "items", "events"] },
    common_mistakes: ["把 outline 当作最终提取结果", "让 MCP 代替主 AI 阅读和理解全文"],
    next_tools: ["submit_extraction_result"],
  },
  submit_extraction_result: {
    tool: "submit_extraction_result",
    purpose: "提交主 AI 从原始材料中提取出的结构化事实。",
    when_to_call: "主 AI 已根据 outline 完成事实提取后。",
    required_fields: ["project_id", "title", "characters", "world", "items", "events"],
    example_input: { project_id: "project_xxx", title: "项目", characters: [], world: [], items: [], events: [], sourceRefs: [] },
    common_mistakes: ["把原始全文塞进 characters/world 字段", "脑补来源中没有的信息"],
    next_tools: ["plan_worldbook_entries"],
  },
  plan_worldbook_entries: {
    tool: "plan_worldbook_entries",
    purpose: "根据 extraction result 生成世界书条目规划表。",
    when_to_call: "结构化事实已提交后。",
    required_fields: ["project_id"],
    example_input: { project_id: "project_xxx" },
    common_mistakes: ["未提交 extraction result 就调用", "把规划表当成可导出的世界书"],
    next_tools: ["create_worldbook_draft_template"],
  },
  create_worldbook_draft_template: {
    tool: "create_worldbook_draft_template",
    purpose: "把条目规划表转换为可填写的 MCP draft JSON 模板。",
    when_to_call: "plan_worldbook_entries 后。",
    required_fields: ["project_id"],
    example_input: { project_id: "project_xxx", save: true },
    common_mistakes: ["直接导出模板而不填写 content", "误以为这是 SillyTavern 最终 JSON"],
    next_tools: ["draft_worldbook_entries", "update_worldbook_draft_entries"],
  },
  draft_worldbook_entries: {
    tool: "draft_worldbook_entries",
    purpose: "保存主 AI 填好的世界书 draft entries，并立即校验。",
    when_to_call: "主 AI 已填写 draft.content 后。",
    required_fields: ["project_id", "entries"],
    example_input: { project_id: "project_xxx", entries: [] },
    common_mistakes: ["content 仍是空模板", "绿灯条目没有 keys"],
    next_tools: ["validate_worldbook_draft", "generate_worldbook_json"],
  },
  generate_worldbook_json: {
    tool: "generate_worldbook_json",
    purpose: "把通过校验的 MCP draft 导出为独立 SillyTavern 世界书 JSON。",
    when_to_call: "validate_worldbook_draft 通过后。",
    required_fields: ["project_id", "worldbook_name"],
    example_input: { project_id: "project_xxx", worldbook_name: "世界书", overwrite: false },
    common_mistakes: ["校验未通过就导出", "output_path 越界"],
    next_tools: ["query_worldbook", "create_character_card_template"],
  },
  create_character_card_template: {
    tool: "create_character_card_template",
    purpose: "创建基础 chara_card_v3 角色卡配置模板。",
    when_to_call: "世界书 draft 完成并通过校验后，且用户需要角色卡。",
    required_fields: ["name"],
    example_input: { project_id: "project_xxx", name: "角色名", include_worldbook: true, greeting_count: 3 },
    common_mistakes: ["未先完成世界书 draft", "把角色详细信息写进 description"],
    next_tools: ["submit_character_card_config"],
  },
  submit_character_card_config: {
    tool: "submit_character_card_config",
    purpose: "保存主 AI 填好的角色卡配置。",
    when_to_call: "主 AI 已填写 first_mes 和 alternate_greetings 后。",
    required_fields: ["project_id", "config"],
    example_input: { project_id: "project_xxx", config: { card: { name: "角色名", first_mes: "..." }, worldbook: { source: "project_draft" } } },
    common_mistakes: ["first_mes 为空", "description 非空"],
    next_tools: ["validate_character_card_config", "generate_character_card_json"],
  },
  generate_character_card_json: {
    tool: "generate_character_card_json",
    purpose: "导出基础 chara_card_v3 角色卡 JSON。如项目启用 MVU，会自动合并 MVU 资产。",
    when_to_call: "角色卡配置、世界书 draft、MVU 配置均通过校验后。",
    required_fields: ["project_id"],
    example_input: { project_id: "project_xxx", overwrite: false },
    common_mistakes: ["未保存 characterCardConfig", "世界书 draft 仍有错误", "启用 MVU 但 schema_script 无效"],
    next_tools: ["query_character_card"],
  },
  create_mvu_schema_template: {
    tool: "create_mvu_schema_template",
    purpose: "创建 MVU/ZOD 变量系统配置模板。",
    when_to_call: "用户需要动态变量、状态栏或后续 EJS 前。通常在角色卡生成前调用。",
    required_fields: ["character_names"],
    example_input: { project_id: "project_xxx", character_names: ["角色A"], variable_list_path: "stat_data" },
    common_mistakes: ["角色名为空", "把完整 HTML 状态栏放进 MVU 配置"],
    next_tools: ["submit_mvu_config"],
  },
  submit_mvu_config: {
    tool: "submit_mvu_config",
    purpose: "保存主 AI 填好的 MVU/ZOD 配置到 project。",
    when_to_call: "主 AI 已调整 schema_script、initvar、update_rules 后。",
    required_fields: ["project_id", "mvu"],
    example_input: { project_id: "project_xxx", mvu: { enabled: true, style: "zod", schema_script: "...", initvar: "...", update_rules: "..." } },
    common_mistakes: ["schema_script 缺少 registerMvuSchema", "initvar 手写 <initvar> 包裹", "混用 MVU beta 风格"],
    next_tools: ["validate_mvu_config", "build_mvu_assets"],
  },
  build_mvu_assets: {
    tool: "build_mvu_assets",
    purpose: "把 MVU 配置构建为世界书条目、regex_scripts 和 tavern_helper scripts。",
    when_to_call: "想在生成角色卡前预览 MVU 资产时。generate_character_card_json 会自动合并这些资产。",
    required_fields: ["project_id"],
    example_input: { project_id: "project_xxx" },
    common_mistakes: ["配置未通过 validate_mvu_config 就构建", "误以为 build_mvu_assets 会直接写角色卡文件"],
    next_tools: ["generate_character_card_json"],
  },
  create_html_beautify_template: {
    tool: "create_html_beautify_template",
    purpose: "创建 HTML 美化配置模板，支持状态栏和全局正则美化。",
    when_to_call: "用户需要状态栏、全局界面美化或更好的变量展示时。",
    required_fields: [],
    example_input: { project_id: "project_xxx", target: "statusbar", theme: "minimal" },
    common_mistakes: ["未启用角色卡生成", "状态栏 HTML 使用全局 CSS 或 script"],
    next_tools: ["submit_html_beautify_config"],
  },
  submit_html_beautify_config: {
    tool: "submit_html_beautify_config",
    purpose: "保存 HTML 美化配置到 project。",
    when_to_call: "主 AI 已调整状态栏 HTML 或全局 regex 后。",
    required_fields: ["project_id", "html"],
    example_input: { project_id: "project_xxx", html: { enabled: true, target: "statusbar", theme: "minimal" } },
    common_mistakes: ["statusbar target 下 html 为空", "全局 regex 缺少 findRegex"],
    next_tools: ["validate_html_beautify_config", "build_html_beautify_assets"],
  },
  build_html_beautify_assets: {
    tool: "build_html_beautify_assets",
    purpose: "把 HTML 美化配置构建为角色卡 regex_scripts。",
    when_to_call: "想在生成角色卡前预览 HTML 美化资产时。generate_character_card_json 会自动合并这些资产。",
    required_fields: ["project_id"],
    example_input: { project_id: "project_xxx" },
    common_mistakes: ["配置未通过 validate_html_beautify_config 就构建", "误以为 build 会直接写角色卡文件"],
    next_tools: ["generate_character_card_json"],
  },
  create_ejs_template: {
    tool: "create_ejs_template",
    purpose: "创建 EJS 动态内容配置模板，支持阶段人设、调色盘和自定义条目。",
    when_to_call: "用户需要根据 MVU 变量动态切换世界书内容时。",
    required_fields: ["character_name"],
    example_input: { project_id: "project_xxx", template_type: "phase_profile", character_name: "角色A" },
    common_mistakes: ["未先启用 MVU", "变量路径未以 stat_data 开头", "阶段条目没有设为 disabled"],
    next_tools: ["submit_ejs_config"],
  },
  submit_ejs_config: {
    tool: "submit_ejs_config",
    purpose: "保存 EJS 动态内容配置到 project。",
    when_to_call: "主 AI 已调整 EJS 控制器和阶段条目内容后。",
    required_fields: ["project_id", "ejs"],
    example_input: { project_id: "project_xxx", ejs: { enabled: true, template_type: "phase_profile", variable_paths: ["stat_data.角色A.好感度"], entries: [] } },
    common_mistakes: ["EJS 标签未闭合", "getwi 未使用 await", "使用 const/let 读取 getvar"],
    next_tools: ["validate_ejs_config", "build_ejs_entries"],
  },
  build_ejs_entries: {
    tool: "build_ejs_entries",
    purpose: "把 EJS 配置构建为将合并进角色卡内嵌世界书的 entries。",
    when_to_call: "想在生成角色卡前预览 EJS 世界书条目时。generate_character_card_json 会自动合并这些条目。",
    required_fields: ["project_id"],
    example_input: { project_id: "project_xxx" },
    common_mistakes: ["未通过 validate_ejs_config 就构建", "误以为 build 会直接写角色卡文件"],
    next_tools: ["generate_character_card_json"],
  },
};

export function getToolUsageGuide(tool: string): ToolUsageGuide | { available_tools: string[]; message: string } {
  return GUIDES[tool] ?? {
    message: `未找到 ${tool} 的专门指南，可先调用 get_worldbook_workflow 获取总体流程。`,
    available_tools: Object.keys(GUIDES).sort(),
  };
}
